services:
  postgres_db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-auth_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-auth_secret}
      POSTGRES_DB: ${POSTGRES_DB:-auth_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-auth_user} -d ${POSTGRES_DB:-auth_db}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  django_app:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=pydj_auth.settings
      - DEBUG=True
      - DB_HOST=postgres_db
      - POSTGRES_HOST=postgres_db
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - django_network

networks:
  django_network:
    driver: bridge

volumes:
  postgres_data:
